server:
  port: 8080
spring:
  application:
    name: spring-data-redis
  session:
    redis:
      namespace: spring:session   #session在redis存储的key值
  redis:    #连接redis
    host: localhost
    port: 6379
    database: 0

