# 连接sqlserver数据库模板

spring:
  application:
    name: springboot-mybatis-plus
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:sqlserver://localhost:1433;DatabaseName=third_party_info
      username: sa
      password: 123456
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      test-on-borrow: true
      test-while-idle: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
      validation-query: select 'x'  # 申请连接时执行的查询语句，用来检测是否连接成功，一般为select 'x'

#mybatis plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: now()
      logic-not-delete-value: "null"
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kim.springboot.mybatisplus.entity.dos,com.kim.springboot.mybatisplus.entity.dtos,com.kim.springboot.mybatisplus.entity.vos
  type-enums-package: com.kim.springboot.mybatisplus.consts     #枚举所在的包

server:
  port: 9000

#swagger
swagger:
  enabled: true
  base-package: com.kim.springboot.mybatisplus.controller

#logging
logging:
  config: classpath:log/logback.xml
  level:
    com.kim.springboot.mybatisplus.mapper: debug  #打印sql日志