spring:
  application:
    name: mongodb-java
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: admin
      password: 123456
      database: mymongo
      option:
        max-connection-idle-time: 60000